import pyautogui
import time
pos = [r"C:\Users\ABHIJITH UDAYAKUMAR\Desktop\ELAB DATA\FAIZ\JAVA", r"C:\Users\ABHIJITH UDAYAKUMAR\Desktop\ELAB DATA\PRIYA\JAVA"]
user = ["RA1931241010033", "RA1931241010003"]
passw = ["JAVALABDD123", "VisuPriya"]
# for i in range(2):
#     pyautogui.click(2688, 33)
#     time.sleep(2)
#     pyautogui.hotkey("alt", "d")
#     pyautogui.typewrite("https://care.srmist.edu.in/mysqlelabsh/")
#     pyautogui.keyDown("enter")
#     pyautogui.keyUp("enter")
#     time.sleep(10)
#     pyautogui.click(1780, 815)
#     time.sleep(2)
#     pyautogui.typewrite(user[i])
#     time.sleep(2)
#     pyautogui.click(1666, 984)
#     time.sleep(2)
#     pyautogui.typewrite(passw[i])
#     time.sleep(2)
#     pyautogui.click(2154, 1104)
#     time.sleep(5)
#     pyautogui.hotkey("alt", "d")
#     pyautogui.typewrite("https://care.srmist.edu.in/mysqlelabsh/login/student/code/dbms/dbms.code.php?id=1&value=0")
#     pyautogui.keyDown("enter")
#     pyautogui.keyUp("enter")
#     time.sleep(5)
#     pyautogui.hotkey("ctrl", "t")
#     pyautogui.typewrite("chrome://settings/downloads")
#     pyautogui.keyDown("enter")
#     pyautogui.keyUp("enter")
#     time.sleep(5)
#     pyautogui.click(2629, 641)
#     time.sleep(3)
#     pyautogui.click(749, 118)
#     pyautogui.typewrite(pos[i])
#     time.sleep(1)
#     pyautogui.keyDown("enter")
#     pyautogui.keyUp("enter")
#     time.sleep(2)
#     pyautogui.click(1122, 1354)
#     time.sleep(2)
#     pyautogui.hotkey("ctrl", "w")
#     time.sleep(2)
#     for j in range(5):
#         print("Starting Question "+str(j+1))
#         pyautogui.click(2700, 1496)
#         time.sleep(5)
#         pyautogui.click(3605, 1811)
#         time.sleep(1)
#         print("Completed Question "+str(j+1))
#         pyautogui.click(3704, 461)
#         time.sleep(5)
#     pyautogui.click(3770, 319)
#     time.sleep(5)
#     pyautogui.hotkey("ctrl", "n")
#     time.sleep(2)
print(pyautogui.position())
url = "https://care.srmist.edu.in/mysqlelabsh/login/student/code/dbms/dbms.code.php?id=1&value="
pyautogui.click(1832, 1744)
for i in range(100):
    time.sleep(0.5)
    pyautogui.hotkey("alt", "d")
    time.sleep(0.5)
    pyautogui.typewrite(url + str(i))
    time.sleep(0.5)
    pyautogui.keyDown("enter")
    time.sleep(0.5)
    pyautogui.keyUp("enter")
    time.sleep(2)
    myScreenshot = pyautogui.screenshot()
    myScreenshot.save('images/dbms/'+str(i + 1) + '.png')